In [2]:
from synergy_transfer.utils.get_data import hello
import pandas as pd

In [17]:
drug_DrugBank_target = pd.read_csv('data/drug_DrugBank_target.csv')
drug_lincs_target = pd.read_csv('data/drug_lincs_target.csv')
drug_TTD_target = pd.read_csv('data/drug_TTD_target.csv')
cell_line = pd.read_csv('data/cell_lines.csv')
cell_line_meta = pd.read_csv('data/cell_line_meta.csv')
cell_line_meta_modified = pd.read_csv('data/cell_line_meta_modified.csv')

In [18]:
drug_DrugBank_target.head()

,Gene,uniprot_protein_acc_id,drugbank_id,drug_name,drug_action_type,drug_status,drug_status2
0,F2,P00734,DB00001,Lepirudin,Inhibitor,Biotech,Approved
1,EGFR,P00533,DB00002,Cetuximab,Antagonist,Biotech,Approved
2,ERBB,P00533,DB00002,Cetuximab,Antagonist,Biotech,Approved
3,ERBB1,P00533,DB00002,Cetuximab,Antagonist,Biotech,Approved
4,HER1,P00533,DB00002,Cetuximab,Antagonist,Biotech,Approved

In [19]:
drug_lincs_target.head()

,Unnamed: 0,dname,chembl_id,inchikey,smiles,cid,molecular_formula,clinical_phase,cid_m,cid_s,stitch_name,drugbank_id,kegg_id,target_genes
0,343,VALPROIC ACID,CHEMBL109,NIJJYAXOARWZEE-UHFFFAOYSA-N,CCCC(CCC)C(=O)O,3121,C8H16O2,4,CIDm00003121,CIDs00003121,valproate,DB00313,D00399,"ABAT,HDAC1,SCN1A,SCN3A,ACADSB,ALDH5A1,HDAC2,HD..."
1,321,PROBUCOL,CHEMBL608,FYPMFJGVHOHGLL-UHFFFAOYSA-N,CC(C)(C)C1=CC(=CC(=C1O)C(C)(C)C)SC(C)(C)SC2=CC...,4912,C31H48O2S2,4,CIDm00004912,CIDs00004912,probucol,DB01599,D00476,"ABCA1,ABCB11,CES1"
2,476,CARBAMAZEPINE,CHEMBL108,FFGPTBGBLSHEPO-UHFFFAOYSA-N,C1=CC=C2C(=C1)C=CC3=CC=CC=C3N2C(=O)N,2554,C15H12N2O,4,CIDm00002554,CIDs00002554,carbamazepine,DB00564,D00252,"ABCB1,CYP1A2,CYP3A4,SCN1A,SCN3A,SCN5A"
3,440,PHENYTOIN,CHEMBL16,CXOFVDLJLONNDW-UHFFFAOYSA-N,C1=CC=C(C=C1)C2(C(=O)NC(=O)N2)C3=CC=CC=C3,1775,C15H12N2O2,4,CIDm00001775,CIDs00001775,phenytoin,DB00252,D00512,"ABCB1,CYP2B6,CYP2C19,CYP3A4,SCN1A,SCN2A,SCN5A"
4,3199,Tesmilifene,CHEMBL26424,NFIXBCVWIPOYCD-UHFFFAOYSA-N,CCN(CC)CCOC1=CC=C(C=C1)CC2=CC=CC=C2,108092,C19H25NO,2,CIDm00108092,CIDs00108092,tesmilifene,DB04905,NaN,"ABCB1,HRH1"

In [20]:
drug_TTD_target.head()

,dname,chembl_id,inchikey,smiles,cid,molecular_formula,clinical_phase,cid_m,cid_s,stitch_name,drugbank_id,kegg_id,target_genes,PUBCHCID,TTD_TARGETS
0,5-FU,CHEMBL185,GHASVSINZRGABV-UHFFFAOYSA-N,C1=C(C(=O)NC(=O)N1)F,3385,C4H3FN2O2,4,CIDm00003385,CIDs00003385,5-fluorouracil,DB00544,D00584,NaN,3385,"Candi TMP1,DPYD,TERT,TYMS"
1,AZD1775,CHEMBL1976040,BKWJAKQVGHWELA-UHFFFAOYSA-N,CC(C)(C1=NC(=CC=C1)N2C3=NC(=NC=C3C(=O)N2CC=C)N...,24856436,C27H32N8O2,2,CIDm24856436,CIDs24856436,MK-1775,DB11740,NaN,NaN,24856436,WEE1
2,BEZ-235,CHEMBL1879463,JOGKUKXHTYWRGZ-UHFFFAOYSA-N,CC(C)(C#N)C1=CC=C(C=C1)N2C3=C4C=C(C=CC4=NC=C3N...,11977753,C30H23N5O,2,CIDm11977753,CIDs11977753,NVP-BEZ235,DB11651,D10552,NaN,11977753,"MTOR,PIK3CG"
3,BORTEZOMIB,CHEMBL325041,GXJABQQUPOEUTA-RDJZCZTQSA-N,B(C(CC(C)C)NC(=O)C(CC1=CC=CC=C1)NC(=O)C2=NC=CN...,387447,C19H25BN4O4,4,CIDm00093860,CIDs00387447,bortezomib,DB00188,D03150,NaN,387447,PRSS1
4,DASATINIB,CHEMBL1421,ZBNZXTGUTAYRHI-UHFFFAOYSA-N,CC1=C(C(=CC=C1)Cl)NC(=O)C2=CN=C(S2)NC3=NC(=NC(...,3062316,C22H26ClN7O2S,4,CIDm03062316,CIDs03062316,dasatinib,DB01254,D03658,NaN,3062316,"LCK,SRC,BCR-ABL1,FYN"

In [21]:
cell_line_meta.head()

,id,name,synonyms,cellosaurus_accession,SANGAR_ID,COSMIC_ID,BROAD_ID,CCLE_ID,tissue,disease_id
0,1,786-0,786-0; 786O; 786-0; 786.O; 786-O RCC; RCC 786-...,CVCL_1051,SIDM00125,905947,ACH-000649,786O_KIDNEY,kidney,C9385
1,2,A2058,A2058; A 2058; A-2058,CVCL_1059,SIDM00797,906792,ACH-000788,A2058_SKIN,skin,C3802
2,3,A2780,A2780; A-2780; 2780; A2780S,CVCL_0134,SIDM00210,906804,ACH-000657,A2780_OVARY,ovary,C7979
3,4,A375,A375; A 375; A375; A375-MEL; A375-mel; A375mel,CVCL_0132,SIDM00795,906793,ACH-000219,A375_SKIN,skin,C3802
4,5,A427,A427; A427,CVCL_1055,SIDM00810,910851,ACH-000757,A427_LUNG,lung,C3512

In [22]:
cell_line_meta_modified.head()

,id,name,synonyms,cellosaurus_accession,SANGAR_ID,COSMIC_ID,BROAD_ID,CCLE_ID,tissue,disease_id
0,1,786-0,786-0; 786O; 786-0; 786.O; 786-O RCC; RCC 786-...,CVCL_1051,SIDM00125,905947,ACH-000649,786O_KIDNEY,kidney,C9385
1,2,A2058,A2058; A 2058; A-2058,CVCL_1059,SIDM00797,906792,ACH-000788,A2058_SKIN,skin,C3802
2,3,A2780,A2780; A-2780; 2780; A2780S,CVCL_0134,SIDM00210,906804,ACH-000657,A2780_OVARY,ovary,C7979
3,4,A375,A375; A 375; A375; A375-MEL; A375-mel; A375mel,CVCL_0132,SIDM00795,906793,ACH-000219,A375_SKIN,skin,C3802
4,5,A427,A427; A427,CVCL_1055,SIDM00810,910851,ACH-000757,A427_LUNG,lung,C3512

In [23]:
cell_line.head()

,name,synonyms,cellosaurus_accession,disease_id,id,tissue_id,depmap_id,cell_model_passport_id,cosmic_id,ccle_name,expression_data
0,786-0,786-0; 786O; 786-0; 786.O; 786-O RCC; RCC 786-...,CVCL_1051,C9385,1,5.0,ACH-000649,SIDM00125,905947.0,786O_KIDNEY,BROAD_DepMap
1,A2058,A2058; A 2058; A-2058,CVCL_1059,C3802,2,10.0,ACH-000788,SIDM00797,906792.0,A2058_SKIN,BROAD_DepMap
2,A2780,A2780; A-2780; 2780; A2780S,CVCL_0134,C7979,3,8.0,ACH-000657,SIDM00210,906804.0,A2780_OVARY,BROAD_DepMap
3,A375,A375; A 375; A375; A375-MEL; A375-mel; A375mel,CVCL_0132,C3802,4,10.0,ACH-000219,SIDM00795,906793.0,A375_SKIN,BROAD_DepMap
4,A427,A427; A427,CVCL_1055,C3512,5,7.0,ACH-000757,SIDM00810,910851.0,A427_LUNG,BROAD_DepMap